/**
 * Generates CLAUDE.md content from a Forge agent architecture.
 *
 * The generated CLAUDE.md instructs Claude Code to follow the agent
 * hierarchy and respect per-agent capability boundaries.
 */

export const CAPABILITY_DESCRIPTIONS = {
  read_files: "Read files from the filesystem",
  write_files: "Write and edit files on the filesystem",
  run_commands: "Execute terminal/shell commands",
  spawn_agents: "Spawn sub-agents to handle tasks in parallel",
  github_read: "Read GitHub issues, PRs, and repository data",
  github_pr: "Create and manage GitHub pull requests",
  github_push: "Push commits to GitHub repositories",
  linear_read: "Read Linear tickets and project data",
  linear_create: "Create new Linear tickets",
  linear_update: "Update existing Linear tickets",
  slack_read: "Read Slack messages and channels",
  slack_send: "Send messages to Slack channels",
  jira_read: "Read Jira tickets and boards",
  jira_create: "Create Jira tickets",
  web_fetch: "Fetch content from URLs",
  web_search: "Perform web searches",
};

const CAPABILITY_RESTRICTIONS = {
  read_files: null, // allowed = no restriction needed
  write_files: "Do NOT write or edit any files",
  run_commands: "Do NOT execute any terminal or shell commands",
  spawn_agents: "Do NOT spawn any sub-agents",
  github_read: null,
  github_pr: "Do NOT create or modify GitHub pull requests",
  github_push: "Do NOT push any commits to GitHub",
  linear_read: null,
  linear_create: "Do NOT create Linear tickets",
  linear_update: "Do NOT modify Linear tickets",
  slack_read: null,
  slack_send: "Do NOT send any Slack messages",
  jira_read: null,
  jira_create: "Do NOT create Jira tickets",
  web_fetch: null,
  web_search: null,
};

export function generateClaudeMd(architecture) {
  const { name, nodes = [], edges = [] } = architecture;
  const lines = [];

  lines.push(`# ${name}`);
  lines.push("");
  lines.push(`> Generated by Forge — agent architecture for Claude Code`);
  lines.push("");

  // Build parent→child relationships from edges
  const childMap = new Map(); // parent → [children]
  const parentMap = new Map(); // child → parent
  for (const edge of edges) {
    if (!childMap.has(edge.source)) childMap.set(edge.source, []);
    childMap.get(edge.source).push(edge.target);
    parentMap.set(edge.target, edge.source);
  }

  // Identify root agents (no parent)
  const roots = nodes.filter((n) => !parentMap.has(n.id));

  lines.push("## Agent Hierarchy");
  lines.push("");

  // Render tree
  function renderTree(nodeId, depth = 0) {
    const node = nodes.find((n) => n.id === nodeId);
    if (!node) return;
    const prefix = depth === 0 ? "" : "  ".repeat(depth) + "- ";
    const roleTag = node.data.role && node.data.role !== "worker" ? ` (${node.data.role})` : "";
    lines.push(`${prefix}**${node.data.label}**${roleTag}`);
    const children = childMap.get(nodeId) || [];
    for (const childId of children) {
      renderTree(childId, depth + 1);
    }
  }

  for (const root of roots) {
    renderTree(root.id);
    lines.push("");
  }

  // Agent definitions with capabilities
  lines.push("## Agent Definitions");
  lines.push("");

  for (const node of nodes) {
    const caps = node.data.capabilities || [];
    const allCapIds = Object.keys(CAPABILITY_DESCRIPTIONS);
    const disabledCaps = allCapIds.filter((id) => !caps.includes(id));
    const restrictions = disabledCaps
      .map((id) => CAPABILITY_RESTRICTIONS[id])
      .filter(Boolean);

    lines.push(`### ${node.data.label}`);
    lines.push("");
    lines.push(`- **Role**: ${node.data.role}`);

    if (caps.length > 0) {
      lines.push(`- **Allowed capabilities**:`);
      for (const cap of caps) {
        lines.push(`  - ${CAPABILITY_DESCRIPTIONS[cap] || cap}`);
      }
    }

    if (restrictions.length > 0) {
      lines.push(`- **Restrictions**:`);
      for (const r of restrictions) {
        lines.push(`  - ${r}`);
      }
    }

    // File restrictions
    const fileRestrictions = node.data.fileRestrictions || [];
    if (fileRestrictions.length > 0) {
      const patterns = fileRestrictions.map((p) => `\`${p}\``).join(", ");
      lines.push(`- **File access**: Only touch files matching: ${patterns}`);
    }

    // Children
    const children = childMap.get(node.id) || [];
    if (children.length > 0) {
      const childNames = children
        .map((cid) => nodes.find((n) => n.id === cid)?.data.label)
        .filter(Boolean);
      lines.push(`- **Delegates to**: ${childNames.join(", ")}`);
    }

    // Parent
    const parentId = parentMap.get(node.id);
    if (parentId) {
      const parentNode = nodes.find((n) => n.id === parentId);
      if (parentNode) {
        lines.push(`- **Reports to**: ${parentNode.data.label}`);
      }
    }

    // System prompt
    if (node.data.systemPrompt) {
      lines.push("");
      lines.push(`#### System Prompt`);
      lines.push("");
      lines.push(node.data.systemPrompt);
    }

    lines.push("");
  }

  // Workflow rules
  lines.push("## Workflow Rules");
  lines.push("");
  lines.push("1. Each agent must stay within its defined capabilities. Do not perform actions outside your role.");
  lines.push("2. Supervisor agents coordinate work by delegating to their child agents.");
  lines.push("3. Worker agents complete their assigned tasks and report results back.");
  lines.push("4. Reviewer agents validate output quality and correctness before reporting back.");
  lines.push("5. Tester agents write and run tests to verify functionality.");
  lines.push("6. Planner agents break down tasks into subtasks and create execution plans.");
  lines.push("7. When spawning a sub-agent, include the agent's name and capabilities in the prompt.");
  lines.push("8. Respect the hierarchy — only delegate to agents defined as your children.");
  lines.push("9. If file access restrictions are defined, only read or modify files matching those patterns.");
  lines.push("");

  return lines.join("\n");
}
