import React, { useState } from "react";
import { X, MessageSquare, GitPullRequest, Send, Bell, CheckCircle } from "lucide-react";
import clsx from "clsx";

const ACTION_TYPES = [
  { id: "github_comment", label: "GitHub Comment", icon: MessageSquare, desc: "Post a comment on a PR or issue" },
  { id: "approve_pr", label: "Approve PR", icon: CheckCircle, desc: "Approve the pull request" },
  { id: "create_pr", label: "Create PR", icon: GitPullRequest, desc: "Create a new pull request" },
  { id: "slack_message", label: "Slack Message", icon: Send, desc: "Send a message to a Slack channel" },
  { id: "notification", label: "Notification", icon: Bell, desc: "Send a Forge notification" },
];

export function ActionPanel({ node, onUpdate, onClose }) {
  const data = node?.data || {};
  const [actionType, setActionType] = useState(data.actionType || "notification");
  const [label, setLabel] = useState(data.label || "");
  const [config, setConfig] = useState(data.config || {});

  function handleTypeChange(type) {
    setActionType(type);
    setConfig({});
    onUpdate({ actionType: type, config: {} });
  }

  function updateConfig(key, val) {
    const newConfig = { ...config, [key]: val };
    setConfig(newConfig);
    onUpdate({ config: newConfig });
  }

  return (
    <div className="w-72 border-l border-forge-border flex flex-col bg-forge-surface">
      <div className="px-4 py-3 border-b border-forge-border flex items-center justify-between">
        <p className="text-xs font-semibold text-forge-text">Action Config</p>
        <button onClick={onClose} className="text-forge-muted hover:text-forge-text">
          <X size={14} />
        </button>
      </div>

      <div className="flex-1 overflow-y-auto p-4 flex flex-col gap-4">
        {/* Label */}
        <div>
          <label className="text-[10px] text-forge-muted uppercase tracking-wider mb-1 block">Label</label>
          <input
            value={label}
            onChange={(e) => { setLabel(e.target.value); onUpdate({ label: e.target.value }); }}
            className="w-full bg-forge-bg border border-forge-border rounded-lg px-3 py-2 text-xs text-forge-text outline-none focus:border-forge-muted"
          />
        </div>

        {/* Action Type */}
        <div>
          <label className="text-[10px] text-forge-muted uppercase tracking-wider mb-2 block">Action Type</label>
          <div className="flex flex-col gap-1.5">
            {ACTION_TYPES.map((a) => {
              const Icon = a.icon;
              return (
                <button
                  key={a.id}
                  onClick={() => handleTypeChange(a.id)}
                  className={clsx(
                    "flex items-center gap-2 px-3 py-2 rounded-lg text-left transition-colors",
                    actionType === a.id
                      ? "bg-green-500/20 border border-green-400/40"
                      : "bg-forge-bg border border-forge-border hover:border-forge-muted"
                  )}
                >
                  <Icon size={12} className={actionType === a.id ? "text-green-400" : "text-forge-muted"} />
                  <div>
                    <p className="text-[10px] font-semibold text-forge-text">{a.label}</p>
                    <p className="text-[9px] text-forge-muted">{a.desc}</p>
                  </div>
                </button>
              );
            })}
          </div>
        </div>

        {/* Type-specific config */}
        {actionType === "github_comment" && (
          <div>
            <label className="text-[10px] text-forge-muted uppercase tracking-wider mb-1 block">Comment Template</label>
            <textarea
              value={config.template || ""}
              onChange={(e) => updateConfig("template", e.target.value)}
              rows={4}
              placeholder="## Review Summary\n\n{{output}}\n\n---\n_Generated by Forge_"
              className="w-full bg-forge-bg border border-forge-border rounded-lg px-3 py-2 text-xs text-forge-text font-mono resize-y outline-none focus:border-forge-muted"
            />
            <p className="text-[9px] text-forge-muted mt-1">
              Use {"{{output}}"} for agent output, {"{{agent}}"} for agent name
            </p>
          </div>
        )}

        {actionType === "create_pr" && (
          <div className="flex flex-col gap-3">
            <div>
              <label className="text-[10px] text-forge-muted uppercase tracking-wider mb-1 block">Branch Name Template</label>
              <input
                value={config.branch || ""}
                onChange={(e) => updateConfig("branch", e.target.value)}
                placeholder="forge/{{workflow}}-{{timestamp}}"
                className="w-full bg-forge-bg border border-forge-border rounded-lg px-3 py-2 text-xs text-forge-text font-mono outline-none focus:border-forge-muted"
              />
            </div>
            <div>
              <label className="text-[10px] text-forge-muted uppercase tracking-wider mb-1 block">PR Title Template</label>
              <input
                value={config.title || ""}
                onChange={(e) => updateConfig("title", e.target.value)}
                placeholder="[Forge] {{workflow}} results"
                className="w-full bg-forge-bg border border-forge-border rounded-lg px-3 py-2 text-xs text-forge-text font-mono outline-none focus:border-forge-muted"
              />
            </div>
          </div>
        )}

        {actionType === "slack_message" && (
          <div className="flex flex-col gap-3">
            <div>
              <label className="text-[10px] text-forge-muted uppercase tracking-wider mb-1 block">Channel</label>
              <input
                value={config.channel || ""}
                onChange={(e) => updateConfig("channel", e.target.value)}
                placeholder="#engineering"
                className="w-full bg-forge-bg border border-forge-border rounded-lg px-3 py-2 text-xs text-forge-text outline-none focus:border-forge-muted"
              />
            </div>
            <div>
              <label className="text-[10px] text-forge-muted uppercase tracking-wider mb-1 block">Message Template</label>
              <textarea
                value={config.template || ""}
                onChange={(e) => updateConfig("template", e.target.value)}
                rows={3}
                placeholder="Workflow complete: {{workflow}}\nResults: {{output}}"
                className="w-full bg-forge-bg border border-forge-border rounded-lg px-3 py-2 text-xs text-forge-text font-mono resize-y outline-none focus:border-forge-muted"
              />
            </div>
          </div>
        )}

        {actionType === "notification" && (
          <div>
            <label className="text-[10px] text-forge-muted uppercase tracking-wider mb-1 block">Message</label>
            <textarea
              value={config.template || ""}
              onChange={(e) => updateConfig("template", e.target.value)}
              rows={3}
              placeholder="Workflow {{workflow}} completed successfully"
              className="w-full bg-forge-bg border border-forge-border rounded-lg px-3 py-2 text-xs text-forge-text resize-y outline-none focus:border-forge-muted"
            />
          </div>
        )}
      </div>
    </div>
  );
}
